package com.hariSolution.mapper;

import com.hariSolution.model.ShadowTripDetails;
import com.hariSolution.model.TripDetails;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(componentModel = "spring")  // Marks this interface as a MapStruct mapper and integrates with Spring
public interface ShadowTripDetailsMapper {

    // Creates an instance of ShadowTripDetailsMapper that will be automatically generated by MapStruct at compile-time
    ShadowTripDetailsMapper INSTANCE = Mappers.getMapper(ShadowTripDetailsMapper.class);

    // Method to convert TripDetails entity to ShadowTripDetails entity
    public ShadowTripDetails toTripDetails(TripDetails tripDetails);
}
